site_name: "MichiJS"
site_author: Lucas Segurado
site_url: "https://michijs.com"
repo_url: https://github.com/michijs/michijs
site_dir: build
copyright: "Copyright &copy; 2020 MichiJS"
theme:
  name: mkdocs
  font: false
  language: en
  favicon: https://raw.githubusercontent.com/michijs/art/refs/heads/main/logo-with-background-round.svg
  logo: https://raw.githubusercontent.com/michijs/art/refs/heads/main/logo-with-background-round.svg
  palette:
    - scheme: slate          # modo oscuro al switchear
      primary: slate
      accent: slate
  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - navigation.prune
    - toc.integrate
    - toc.follow
    - navigation.top
    - navigation.sections
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.instant.preview
    - search.highlight
    - search.suggest
nav:
  - Develop with MichiJS: index.md
  - Changelog: changelog.md
  - License: license.md
  # - Products: products.md
  - Support: support.md
extra_css:
  - stylesheets/extra.css
watch:
  - docs/*
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/michijs
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/michijs
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/@michijs_
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/michijs.fw
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/michijs_
  generator: false
  version:
    provider: mike
    alias: true
    version_selector: true
markdown_extensions:
  - def_list:
  - toc:
      toc_depth: 3
  - md_in_html:
  - attr_list:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format